/* Lógico_1: */

CREATE TABLE PESSOA_FISICA (
    cpf INTEGER,
    id SERIAL PRIMARY KEY
);

CREATE TABLE PESSOA_JURIDICA (
    cnpj INTEGER,
    inscricaoEstadual INTEGER,
    cnae INTEGER,
    id SERIAL PRIMARY KEY
);

CREATE TABLE ENDERECO_ENTIDADE_SOCIAL (
    cep INTEGER,
    rua VARCHAR(255),
    numero INTEGER,
    bairro VARCHAR(255),
    cidade VARCHAR(255),
    estado CHAR(2),
    id SERIAL PRIMARY KEY,
    pais VARCHAR(20),
    nome VARCHAR(255)
);

CREATE TABLE NOTA_FISCAL (
    id SERIAL PRIMARY KEY,
    chaveAcesso INTEGER,
    numero INTEGER,
    serie INTEGER,
    dataEmissao TIMESTAMP,
    tributoFederal DECIMAL,
    tributoEstadual DECIMAL,
    idVendedor SERIAL,
    idComprador SERIAL
);

CREATE TABLE ITEM (
    id SERIAL PRIMARY KEY,
    quantidade DECIMAL,
    valor DECIMAL,
    desconto DECIMAL,
    tributos DECIMAL,
    discriminacao VARCHAR(255),
    idNotaFiscal SERIAL
);

CREATE TABLE SERVICO (
    id SERIAL PRIMARY KEY
);

CREATE TABLE PRODUTO (
    cEnqLegal INTEGER,
    cfop INTEGER,
    frete DECIMAL,
    id SERIAL PRIMARY KEY
);
 
ALTER TABLE PESSOA_FISICA ADD CONSTRAINT FK_PESSOA_FISICA_2
    FOREIGN KEY (id)
    REFERENCES ??? (???);
 
ALTER TABLE PESSOA_JURIDICA ADD CONSTRAINT FK_PESSOA_JURIDICA_2
    FOREIGN KEY (id)
    REFERENCES ??? (???);
 
ALTER TABLE NOTA_FISCAL ADD CONSTRAINT FK_NOTA_FISCAL_2
    FOREIGN KEY (idVendedor, idComprador)
    REFERENCES ??? (???);
 
ALTER TABLE ITEM ADD CONSTRAINT FK_ITEM_2
    FOREIGN KEY (idNotaFiscal)
    REFERENCES NOTA_FISCAL (id)
    ON DELETE RESTRICT;
 
ALTER TABLE SERVICO ADD CONSTRAINT FK_SERVICO_2
    FOREIGN KEY (id)
    REFERENCES ITEM (id)
    ON DELETE CASCADE;
 
ALTER TABLE PRODUTO ADD CONSTRAINT FK_PRODUTO_2
    FOREIGN KEY (id)
    REFERENCES ITEM (id)
    ON DELETE CASCADE;