# /watchman/docker/Dockerfile.flask

FROM python:3.11-slim-buster

WORKDIR /app

COPY requirements.flask.txt .
RUN pip install --no-cache-dir -r requirements.flask.txt

COPY ./run.py .                
COPY ./app/ ./app/               

EXPOSE 8000

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "run:app"]